### ISSUE TITLE
Just need to view locally

### ISSUE THREAD

**Issue by SmithersA** [pattern-lab/patternlab-node#1013]
I am using Pattern Lab Node `whatever is on here today` on `Mac`, with Node `v11.2.0`, using a `node` Edition.

##### Expected Behavior
??:serve
##### Actual Behavior
What is the terminal command to start viewing this patternlab locally after following all the instructions? The documentation choices starting with gulp- or grunt- are no longer valid when using (https://github.com/pattern-lab/patternlab-node) in Node edition (mustache-) because it said that I wouldn't need to install those
##### Steps to Reproduce
 Which edition do you want to use (defaults to edition-node)? edition-node
? Which starterkit do you want to use? starterkit-mustache-materialdesign
? Are you happy with your choices? (Hit enter for YES)? Yes
✔ ⊙ patternlab → Installed edition: @pattern-lab/edition-node
✔ ⊙ patternlab → Installed starterkit: starterkit-mustache-materialdesign
✔ ⊙ patternlab → Yay ☺. Pattern Lab Node was successfully initialized in ../new-project
NMAAHC-39822:new-project smithersa$ node patternlab:serve
internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module '/Users/SmithersA/patternlab-node-dev/new-project/patternlab:serve'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:775:12)
    at startup (internal/bootstrap/node.js:300:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:826:3)
NMAAHC-39822:new-project smithersa$ gulp patternlab:serve
-bash: gulp: command not found
NMAAHC-39822:new-project smithersa$ patternlab:serve
-bash: patternlab:serve: command not found
NMAAHC-39822:new-project smithersa$ php patternlab:serve
Could not open input file: patternlab:serve

**Comment by JosefBredereck** [comment]
You will find the answers here https://github.com/pattern-lab/patternlab-node/tree/dev/packages/edition-node

just in case this doesn't work also. In the package.json file you will find scirpts that are predefined.

```JSON
"scripts": {
   "pl:build": "patternlab build --config ./patternlab-config.json",
   "pl:help": "patternlab --help",
   "pl:install": "patternlab install --config ./patternlab-config.json",
   "pl:serve": "patternlab serve --config ./patternlab-config.json",
   "pl:version": "patternlab --version"
}
