### ISSUE TITLE
patternlab serve fails after successful build

### ISSUE THREAD

**Issue by makeaweli** [pattern-lab/patternlab-node#1032]
I am using Pattern Lab Node `v3.0.1` on `Linux`, with Node `v8.16`, using a `Gulp` Edition.

##### Expected Behavior
After build I expect Patternlab to watch for file modifications.
##### Actual Behavior

Successfully builds and then error outs the following:

```
Built Pattern Lab front end
Pattern Lab is being served from http://127.0.0.1:3000
(node:411) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.cp.once.code (/opt/node_modules/opn/index.js:84:13)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Socket.stream.socket.on (internal/child_process.js:336:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:561:12)
(node:411) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:411) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

##### Steps to Reproduce

Using docker:
```
docker run -it --rm -p 3000:3000 -v ~/Sites/patternlab3:/opt node:8.16-alpine /bin/sh

./node_modules/.bin/patternlab init -p /opt -e @pattern-lab/edition-node-gulp \
-k @pattern-lab/starterkit-mustache-demo
```

**Comment by makeaweli** [comment]
Fixed: modify `patternlab-config.json` to prevent the patternlab server to open a browser:

`"serverOptions": {
    "open": false
  },`

Error caused by 
`patternlab-node/packages/live-server/index.js`

defaulting to opening a browser. However on headless environments (I'm using Docker) this results in the `UnhandledPromiseRejectionWarning`
