### ISSUE TITLE
npm create pattern-lab with specified directory and starterkit broken

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#1157]
install starterkit needs to be `projectDir` aware

workaround:

`mkdir my-project && cd my-project` before you `npm create pattern-lab`
then, specify the current directory as the install target

**Comment by designermonkey** [comment]
For me, even following the above step, the install hangs:

```
Projects mkdir patternlab && cd patternlab
➜  patternlab npm create pattern-lab           
? Please specify a directory for your Pattern Lab project. ./
? What templating language do you want to use with Pattern Lab? Handlebars
? What initial patterns do you want included in your project? Blank project (no patterns)
? Are you happy with your choices? (Hit enter for YES)? Yes
⠙ ⊙ patternlab → Installing edition: @pattern-lab/edition-node
```

**Comment by rutger1140** [comment]
Same as [above](https://github.com/pattern-lab/patternlab-node/issues/1157#issuecomment-636490676).

My installation step hangs as well. On MacOS 10.15.6 I've tried: node 8.17, 10.19, 12.18, 14.8 to no avail.  🤷

**Comment by gwhobbs** [comment]
Same for me as well. macOS 10.15.6, node 12.18, and in Ubuntu Docker image with node 10.19. 

The workaround mentioned above does not work for me. 

```
⊙ patternlab → Installing edition: @pattern-lab/edition-node(node:7701) UnhandledPromiseRejectionWarning: Error: Cannot find module '@pattern-lab/edition-node/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.resolve (internal/modules/cjs/helpers.js:33:19)
    at resolveFileInPackage (/root/.npm/_npx/7667/lib/node_modules/create-pattern-lab/node_modules/@pattern-lab/core/src/lib/resolver.js:10:18)
    at resolvePackageFolder (/root/.npm/_npx/7667/lib/node_modules/create-pattern-lab/node_modules/@pattern-lab/core/src/lib/resolver.js:18:23)
    at resolveDirInPackage (/root/.npm/_npx/7667/lib/node_modules/create-pattern-lab/node_modules/@pattern-lab/core/src/lib/resolver.js:26:20)
    at /root/.npm/_npx/7667/lib/node_modules/create-pattern-lab/node_modules/@pattern-lab/cli/bin/install-edition.js:38:7
    at Generator.next (<anonymous>)
    at spwn (/root/.npm/_npx/7667/lib/node_modules/create-pattern-lab/node_modules/@pattern-lab/cli/bin/utils.js:75:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:7701) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7701) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ringods** [comment]
@gwhobbs your problem is something else. This is filed as #1257
