### ISSUE TITLE
Installation is hanging at ⊙ patternlab → Installing edition: @pattern-lab/edition-node

### ISSUE THREAD

**Issue by prd409** [pattern-lab/patternlab-node#1265]
I am using Pattern Lab Node `node:50418` on `macOS 10.15.7, with Node 14.5.0`

##### Expected Behavior
Install @pattern-lab/edition-node

##### Actual Behavior
Installation is hanging at ⊙ patternlab → Installing edition: @pattern-lab/edition-node

##### Steps to Reproduce
mkdir patternlab
cd patternlab
npm create pattern-lab
? Please specify a directory for your Pattern Lab project. ./
? What templating language do you want to use with Pattern Lab? Handlebars
? What initial patterns do you want included in your project? Handlebars base patterns (some basic patterns to get started with)
? Are you happy with your choices? (Hit enter for YES)? Yes
⊙ patternlab → Installing edition: @pattern-lab/edition-node(node:50418) UnhandledPromiseRejectionWarning: Error: Cannot find module '@pattern-lab/edition-node/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at resolveFileInPackage (/Users/prd/.npm/_npx/50266/lib/node_modules/create-pattern-lab/node_modules/@pattern-lab/core/src/lib/resolver.js:10:18)
    at resolvePackageFolder (/Users/prd/.npm/_npx/50266/lib/node_modules/create-pattern-lab/node_modules/@pattern-lab/core/src/lib/resolver.js:18:23)
    at resolveDirInPackage (/Users/prd/.npm/_npx/50266/lib/node_modules/create-pattern-lab/node_modules/@pattern-lab/core/src/lib/resolver.js:26:20)
    at /Users/prd/.npm/_npx/50266/lib/node_modules/create-pattern-lab/node_modules/@pattern-lab/cli/bin/install-edition.js:38:7
    at Generator.next (<anonymous>)
    at spwn (/Users/prd/.npm/_npx/50266/lib/node_modules/create-pattern-lab/node_modules/@pattern-lab/cli/bin/utils.js:75:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:50418) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:50418) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
⠋ ⊙ patternlab → Installing edition: @pattern-lab/edition-node

It hangs here. Tried above steps repeatedly. Same result each time.

**Comment by prd409** [comment]
Just saw this is same issue as #1257. Tried the work-around listed there. That got me up and running so closing this dupe issue. Keep up the good work, guys!
