### ISSUE TITLE
Patternlinks in data gives error on windows systems

### ISSUE THREAD

**Issue by bramsmulders** [pattern-lab/patternlab-node#409]
I am using Pattern Lab Node `v2.3.0` on `Windows`, with Node `v4.4.1`, using the `Gulp` Edition.

##### Expected Behavior
Patternlinks like: 
```
"foo": {
    "bar": "link.to-pattern"
}
```
Should lik to the linked pattern

##### Actual Behavior
On windows the compiler gives the following error:
```
There was an error parsing JSON for data.json
{ [SyntaxError: Bad string at line 1 column 5944 of the JSON5 data. Still to rea
d: "03-templates-00-user"]
  message: 'Bad string at line 1 column 5944 of the JSON5 data. Still to read: "
03-templates-00-user"',
  at: 5943,
  lineNumber: 1,
  columnNumber: 5944 }
[11:46:48] 'patternlab' errored after 301 ms
[11:46:48] TypeError: Cannot set property 'patternLabHead' of undefined
    at buildPatterns (D:\data\inetpub\oypo\Sources\Oypo.Web.UI\static\node_modul
es\patternlab-node\core\lib\patternlab.js:284:36)
    at Object.build (D:\data\inetpub\oypo\Sources\Oypo.Web.UI\static\node_module
s\patternlab-node\core\lib\patternlab.js:391:7)
    at Gulp.<anonymous> (D:\data\inetpub\oypo\Sources\Oypo.Web.UI\static\gulpfil
e.js:440:8)
    at module.exports (D:\data\inetpub\oypo\Sources\Oypo.Web.UI\static\node_modu
les\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (D:\data\inetpub\oypo\Sources\Oypo.Web.UI\stat
ic\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (D:\data\inetpub\oypo\Sources\Oypo.Web.UI\stat
ic\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (D:\data\inetpub\oypo\Sources\Oypo.Web.UI\static\
node_modules\gulp\node_modules\orchestrator\index.js:134:8)
    at C:\Users\des\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:20
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
```
Whereas on a mac everything just works as expected.

**Comment by bmuenzenmeyer** [comment]
@bramsmulders confirmed bug and pushed a small fix. confirmed it works on Windows. Curious if it works on Mac too. can you alter your package.json to point to `pattern-lab/patternlab-node#dev` and see if this resolves your issue?

I had to peel back a couple more things I was trying to do with `path.sep()`, but I may revisit that.

**Comment by bramsmulders** [comment]
Seems to be working correctly on Mac to!
