### ISSUE TITLE
Incremental Builds: RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by SteffiB** [pattern-lab/patternlab-node#705]
I am using Pattern Lab Node `v2.11.1` on `Mac`, with Node `v6.11.3`, using the `Gulp` Edition.

When trying to use the incremental build feature I am running in a "Maximum call stack size exceeded" - error. `cleanPublic` is set to `false`. 

The console output looks like this:
```
[14:26:53] Starting 'patternlab:build'...
Incremental builds enabled.
[14:27:00] 'patternlab:build' errored after 7.36 s
[14:27:00] RangeError: Maximum call stack size exceeded
    at RegExp.exec (native)
    at RegExp.test (native)
    at isKey (/xxx/node_modules/lodash/lodash.js:6348:28)
    at castPath (/xxx/node_modules/lodash/lodash.js:4470:14)
    at hasPath (/xxx/node_modules/lodash/lodash.js:6159:14)
    at Function.has (/xxx/node_modules/lodash/lodash.js:13147:32)
    at Graph.setEdge (/xxx/node_modules/graphlib/lib/graph.js:383:9)
    at applyReverse (/xxx/node_modules/patternlab-node/core/lib/pattern_graph.js:198:22)
    at Object.applyReverse (/xxx/node_modules/patternlab-node/core/lib/pattern_graph.js:216:7)
    at Object.applyReverse (/xxx/node_modules/patternlab-node/core/lib/pattern_graph.js:217:12)
    at Object.applyReverse (/xxx/node_modules/patternlab-node/core/lib/pattern_graph.js:217:12)
    at Object.applyReverse (/xxx/node_modules/patternlab-node/core/lib/pattern_graph.js:217:12)
    at Object.applyReverse (/xxx/node_modules/patternlab-node/core/lib/pattern_graph.js:217:12)
    at Object.applyReverse (/xxx/node_modules/patternlab-node/core/lib/pattern_graph.js:217:12)
    at Object.applyReverse (/xxx/node_modules/patternlab-node/core/lib/pattern_graph.js:217:12)
    at Object.applyReverse (/xxx/node_modules/patternlab-node/core/lib/pattern_graph.js:217:12)
    at Object.applyReverse (/xxx/node_modules/patternlab-node/core/lib/pattern_graph.js:217:12)
    at Object.applyReverse (/xxx/node_modules/patternlab-node/core/lib/pattern_graph.js:217:12)
    at Object.applyReverse (/xxx/node_modules/patternlab-node/core/lib/pattern_graph.js:217:12)
    at Object.applyReverse (/xxx/node_modules/patternlab-node/core/lib/pattern_graph.js:217:12)
    at Object.applyReverse (/xxx/node_modules/patternlab-node/core/lib/pattern_graph.js:217:12)
    at Object.applyReverse (/xxx/node_modules/patternlab-node/core/lib/pattern_graph.js:217:12)
    at Object.applyReverse (/xxx/node_modules/patternlab-node/core/lib/pattern_graph.js:217:12)
    at Object.applyReverse (/xxx/node_modules/patternlab-node/core/lib/pattern_graph.js:217:12)
    at Object.applyReverse (/xxx/node_modules/patternlab-node/core/lib/pattern_graph.js:217:12)
    at Object.applyReverse (/xxx/node_modules/patternlab-node/core/lib/pattern_graph.js:217:12)
    at Object.applyReverse (/xxx/node_modules/patternlab-node/core/lib/pattern_graph.js:217:12)
    at Object.applyReverse (/xxx/node_modules/patternlab-node/core/lib/pattern_graph.js:217:12)
    at Object.applyReverse (/xxx/node_modules/patternlab-node/core/lib/pattern_graph.js:217:12)
    at Object.applyReverse (/xxx/node_modules/patternlab-node/core/lib/pattern_graph.js:217:12)
    at Object.applyReverse (/xxx/node_modules/patternlab-node/core/lib/pattern_graph.js:217:12)
    at Object.applyReverse (/xxx/node_modules/patternlab-node/core/lib/pattern_graph.js:217:12)
    at Object.applyReverse (/xxx/node_modules/patternlab-node/core/lib/pattern_graph.js:217:12)
    at Object.applyReverse (/xxx/node_modules/patternlab-node/core/lib/pattern_graph.js:217:12)
```

When I change `cleanPublic` to `true` everything is working fine.

Some more informations:
- I am using patternlab-node with handlbars-templates
- the time building all patterns (without incremental building) takes ca. 1.7 min
- I have around 600 patterns (including all atoms, molecules, organisms, templates, pages)

Hope anyone can help?

**Comment by bmuenzenmeyer** [comment]
@SteffiB thanks for the thorough report! Sorry this is happening to you, as the performance benefits are great. Has this ever worked for you, or is it your first time attempting to run with incremental builds on?

any change in behavior if you run the following?

```
gulp -- patternlab:serve --stack_size=4096
```

@tburny I thought you'd like to see this - I will try to dig in and understand what's going on too.

**Comment by SteffiB** [comment]
It is the first time attempting to run with incremental builds on.

Unfortunately that has no impact on the result, still same error message.

**Comment by tburny** [comment]
A question ahead: How many patterns do you roughly have in your Patternlab?

Internally incremental builds use a dependency graph of patterns. This graph is traversed *recursively* in order to mark changed files and their dependencies for rebuild, plus a few other things.
That means for larger Pattern Lab instances the call stack can become quite large.
For the time being try to increase the default stack size, as @bmuenzenmeyer mentioned.

Maybe I can figure out how to turn the recursion into something iterative in the future.

**Comment by SteffiB** [comment]
I just found the Problem. It is not the count of patterns.

Our navigation handlebars templates look like this:

nav__level.hbs
```
...
{{# subLevelItems }}
    {{> molecules-nav__item }}
 {{/ subLevelItems }}
...
```

nav__item.hbs
```
...
{{#if subLevelItems }}
    {{> molecules-nav__level }}
{{/if }}
...
```

When building the dependency graph, it runs into an endless loop because these two templates are related on each other. Any suggestions on this?

**Comment by bmuenzenmeyer** [comment]
good sleuthing @SteffiB - I tried to find a similar issue because this is reminiscent (perhaps it was only a gitter chat) - I think the potential resolution was to unfortunately avoid the recursion, if that meant making a one off pattern to support your data

**Comment by tburny** [comment]
Some things we could do here:
* Improve pattern engines: Each pattern has a certain set of data. Maybe it is possible to ask for included patterns with the data as context, instead of a global context-free detection. 
* Add detection for circular references
* Skip using ordered pattern compilation if the pattern engine always expands partials, add an override configuration flag for this behavior. This way we can get rid of recursions when rendering patterns. However the recursion is moved to resolving all partials then.

**Comment by tburny** [comment]
@SteffiB Did it help with your problem?
