### ISSUE TITLE
[cli] Fix tests when running in Travis

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node#858]
As part of #832 and #851 we had lerna run all packages' `npm test` command. For some reason, the CLI tests are [failing when run in Travis ](https://travis-ci.org/pattern-lab/patternlab-node/builds/377837608) but not locally.

This issue should change the command in the CLI `package.json` from `test:separate` back to `test` and resolve why the tests fail.

**Comment by bmuenzenmeyer** [comment]
@raphaelokon i could still use help with this if you ever have time

**Comment by bmuenzenmeyer** [comment]
It appears as if many tests are now failing locally too. I need to dig in and learn more about the CLI it seems.

**Comment by JosefBredereck** [comment]
Is this still an issue?

**Comment by bmuenzenmeyer** [comment]
yes - the CLI tests have been turned off for a while. My understanding of that codebase, unit testing, and CLIs in general has increases since then, so I hope to revisit some day

**Comment by JosefBredereck** [comment]
I will investigate that the next days to have a clear cli package. Also, the cli needs a little bit of an overhaul and that's another cool topic.

**Comment by bmuenzenmeyer** [comment]
> Also, the cli needs a little bit of an overhaul and that's another cool topic.

agreed ! 

I really appreciate your help!

**Comment by bmuenzenmeyer** [comment]
I ran the CLI tests for the first time in a LONG time just now. This is what they report:

brian@DESKTOP-TCM0GPM MINGW64 /d/src/patternlab-node/packages/cli (dev)
$ yarn test:separate
yarn run v1.19.1
$ tap ./test/*.test.js --reporter spec --timeout=120

./test/build.test.js
  Build ->
    √ throws when config is empty
    √ throws when config is not of type object
    √ --patterns-only throws when config is empty
    √ --patterns-only throws when config is not of type object
    √ returns a bool
    √ --patterns-only returns a bool

./test/cli-build.test.js
  Init and build ->
    √ should build all files into public dir
    1) with an annotations dir
    2) with a css dir
    3) with a images dir
    4) with a styleguide dir

./test/cli-disable.test.js
  Disable ->
    5) Cannot read property '@pattern-lab/plugin-tab' of undefined

./test/cli-enable.test.js
  Enable ->
    6) Cannot read property '@pattern-lab/plugin-tab' of undefined

./test/cli-export.test.js
  Init and export ->
    7) should create patterns.zip

./test/cli-init.test.js
  Init ->
    √ should initialize a Pattern Lab project
    √ with a source dir
    √ with a public dir
    √ with a pattern_exports dir
    8) with a pattern_exports dir

./test/export.test.js
  Export ->
    with options empty
      √ throws when options are empty
    with options not an object
      √ throws when passed options are not of type object

./test/install-plugin.test.js
  Install plugin-tab ->
    √ module should exist after install
    9) and persist it on the patternlab-config.json

./test/install-starterkit.test.js
  Install starterkit-mustache-demo ->
    10) ENOENT: no such file or directory, lstat 'D:\src\patternlab-node\packages\cli\node_modules\@pattern-lab\starterkit-must
ache-demo\dist'

  Install starterkit-mustache-base ->
    √ module should exist after install

  Install starterkit-mustache-bootstrap ->
    √ module should exist after install

  Install starterkit-mustache-foundation ->
    √ module should exist after install

  Install starterkit-mustache-acidtest ->
    √ module should exist after install

  Install starterkit-mustache-materialdesign ->
    √ module should exist after install

./test/replace_config_paths.test.js
  replaceConfigPaths ->
    11) should be ok for newConfig.paths.source.root
    12) should be ok for newConfig.paths.source.patterns
    13) should be ok for newConfig.paths.source.data
    14) should be ok for newConfig.paths.source.meta
    15) should be ok for newConfig.paths.source.annotations
    16) should be ok for newConfig.paths.source.styleguide
    17) should be ok for newConfig.paths.source.patternlabFiles.general-header
    18) should be ok for newConfig.paths.source.patternlabFiles.general-footer
    19) should be ok for newConfig.paths.source.patternlabFiles.patternSection
    20) should be ok for newConfig.paths.source.patternlabFiles.patternSectionSubtype
    21) should be ok for newConfig.paths.source.patternlabFiles.viewall
    22) should be ok for newConfig.paths.source.js
    23) should be ok for newConfig.paths.source.images
    24) should be ok for newConfig.paths.source.fonts
    25) should be ok for newConfig.paths.source.css
    26) should be ok for newConfig.paths.public.root
    27) should be ok for newConfig.paths.public.patterns
    28) should be ok for newConfig.paths.public.data
    29) should be ok for newConfig.paths.public.annotations
    30) should be ok for newConfig.paths.public.styleguide
    31) should be ok for newConfig.paths.public.js
    32) should be ok for newConfig.paths.public.images
    33) should be ok for newConfig.paths.public.fonts
    34) should be ok for newConfig.paths.public.css
    35) should be ok for newConfig.patternExportDirectory

./test/resolve_config.test.js
  resolveConfig ->
    √ should return a config of type object
    √ config should have a paths property
    √ returns false when configPath is not of type string
    √ returns false when configPath is not found

./test/scaffold.test.js
  Scaffold ->
    √ should create project dir
    √ should create source dir
    √ should create public dir
    √ should create export dir

./test/serve.test.js
  Serve ->
    √ throws when config is empty
    √ throws when config is not of type object
    √ throws when no source root dir is set on config
    √ throws when no public root dir is set on config


  31 passing (1m)
  35 failing

  1) ./test/cli-build.test.js Init and build -> with an annotations dir:
     Error: with an annotations dir
      at test/cli-build.test.js:31:7
      at spwn (bin/utils.js:24:413)

  2) ./test/cli-build.test.js Init and build -> with a css dir:
     Error: with a css dir
      at test/cli-build.test.js:35:7
      at spwn (bin/utils.js:24:413)

  3) ./test/cli-build.test.js Init and build -> with a images dir:
     Error: with a images dir
      at test/cli-build.test.js:39:7
      at spwn (bin/utils.js:24:413)

  4) ./test/cli-build.test.js Init and build -> with a styleguide dir:
     Error: with a styleguide dir
      at test/cli-build.test.js:43:7
      at spwn (bin/utils.js:24:413)

  5) ./test/cli-disable.test.js Disable -> Cannot read property '@pattern-lab/plugin-tab' of undefined:
     Error: Cannot read property '@pattern-lab/plugin-tab' of undefined
      at test/cli-disable.test.js:46:21
      at spwn (bin/utils.js:24:413)

  6) ./test/cli-enable.test.js Enable -> Cannot read property '@pattern-lab/plugin-tab' of undefined:
     Error: Cannot read property '@pattern-lab/plugin-tab' of undefined
      at test/cli-enable.test.js:39:21
      at spwn (bin/utils.js:24:413)

  7) ./test/cli-export.test.js Init and export -> should create patterns.zip:
     Error: should create patterns.zip
      at test/cli-export.test.js:27:7
      at spwn (bin/utils.js:24:413)

  8) ./test/cli-init.test.js Init -> with a pattern_exports dir:
     Error: with a pattern_exports dir
      at test/cli-init.test.js:32:7
      at spwn (bin/utils.js:24:413)

  9) ./test/install-plugin.test.js Install plugin-tab -> and persist it on the patternlab-config.json:

      Error: and persist it on the patternlab-config.json
      + expected - actual

      -true
      +false

      at test/install-plugin.test.js:22:7
      at spwn (bin/utils.js:24:413)

  10) ./test/install-starterkit.test.js Install starterkit-mustache-demo -> ENOENT: no such file or directory, lstat 'D:\src\pa
tternlab-node\packages\cli\node_modules\@pattern-lab\starterkit-mustache-demo\dist':
     ENOENT: no such file or directory, lstat 'D:\src\patternlab-node\packages\cli\node_modules\@pattern-lab\starterkit-mustach
e-demo\dist'


  11) ./test/replace_config_paths.test.js replaceConfigPaths -> should be ok for newConfig.paths.source.root:
     Error: should be ok for newConfig.paths.source.root
      at Test.<anonymous> (test/replace_config_paths.test.js:25:9)
      at Object.<anonymous> (test/replace_config_paths.test.js:6:5)

  12) ./test/replace_config_paths.test.js replaceConfigPaths -> should be ok for newConfig.paths.source.patterns:
     Error: should be ok for newConfig.paths.source.patterns
      at Test.<anonymous> (test/replace_config_paths.test.js:25:9)
      at Object.<anonymous> (test/replace_config_paths.test.js:6:5)

  13) ./test/replace_config_paths.test.js replaceConfigPaths -> should be ok for newConfig.paths.source.data:
     Error: should be ok for newConfig.paths.source.data
      at Test.<anonymous> (test/replace_config_paths.test.js:25:9)
      at Object.<anonymous> (test/replace_config_paths.test.js:6:5)

  14) ./test/replace_config_paths.test.js replaceConfigPaths -> should be ok for newConfig.paths.source.meta:
     Error: should be ok for newConfig.paths.source.meta
      at Test.<anonymous> (test/replace_config_paths.test.js:25:9)
      at Object.<anonymous> (test/replace_config_paths.test.js:6:5)

  15) ./test/replace_config_paths.test.js replaceConfigPaths -> should be ok for newConfig.paths.source.annotations:
     Error: should be ok for newConfig.paths.source.annotations
      at Test.<anonymous> (test/replace_config_paths.test.js:25:9)
      at Object.<anonymous> (test/replace_config_paths.test.js:6:5)

  16) ./test/replace_config_paths.test.js replaceConfigPaths -> should be ok for newConfig.paths.source.styleguide:
     Error: should be ok for newConfig.paths.source.styleguide
      at Test.<anonymous> (test/replace_config_paths.test.js:25:9)
      at Object.<anonymous> (test/replace_config_paths.test.js:6:5)

  17) ./test/replace_config_paths.test.js replaceConfigPaths -> should be ok for newConfig.paths.source.patternlabFiles.general
-header:
     Error: should be ok for newConfig.paths.source.patternlabFiles.general-header
      at Test.<anonymous> (test/replace_config_paths.test.js:17:11)
      at Object.<anonymous> (test/replace_config_paths.test.js:6:5)

  18) ./test/replace_config_paths.test.js replaceConfigPaths -> should be ok for newConfig.paths.source.patternlabFiles.general
-footer:
     Error: should be ok for newConfig.paths.source.patternlabFiles.general-footer
      at Test.<anonymous> (test/replace_config_paths.test.js:17:11)
      at Object.<anonymous> (test/replace_config_paths.test.js:6:5)

  19) ./test/replace_config_paths.test.js replaceConfigPaths -> should be ok for newConfig.paths.source.patternlabFiles.pattern
Section:
     Error: should be ok for newConfig.paths.source.patternlabFiles.patternSection
      at Test.<anonymous> (test/replace_config_paths.test.js:17:11)
      at Object.<anonymous> (test/replace_config_paths.test.js:6:5)

  20) ./test/replace_config_paths.test.js replaceConfigPaths -> should be ok for newConfig.paths.source.patternlabFiles.pattern
SectionSubtype:
     Error: should be ok for newConfig.paths.source.patternlabFiles.patternSectionSubtype
      at Test.<anonymous> (test/replace_config_paths.test.js:17:11)
      at Object.<anonymous> (test/replace_config_paths.test.js:6:5)

  21) ./test/replace_config_paths.test.js replaceConfigPaths -> should be ok for newConfig.paths.source.patternlabFiles.viewall
:
     Error: should be ok for newConfig.paths.source.patternlabFiles.viewall
      at Test.<anonymous> (test/replace_config_paths.test.js:17:11)
      at Object.<anonymous> (test/replace_config_paths.test.js:6:5)

  22) ./test/replace_config_paths.test.js replaceConfigPaths -> should be ok for newConfig.paths.source.js:
     Error: should be ok for newConfig.paths.source.js
      at Test.<anonymous> (test/replace_config_paths.test.js:25:9)
      at Object.<anonymous> (test/replace_config_paths.test.js:6:5)

  23) ./test/replace_config_paths.test.js replaceConfigPaths -> should be ok for newConfig.paths.source.images:
     Error: should be ok for newConfig.paths.source.images
      at Test.<anonymous> (test/replace_config_paths.test.js:25:9)
      at Object.<anonymous> (test/replace_config_paths.test.js:6:5)

  24) ./test/replace_config_paths.test.js replaceConfigPaths -> should be ok for newConfig.paths.source.fonts:
     Error: should be ok for newConfig.paths.source.fonts
      at Test.<anonymous> (test/replace_config_paths.test.js:25:9)
      at Object.<anonymous> (test/replace_config_paths.test.js:6:5)

  25) ./test/replace_config_paths.test.js replaceConfigPaths -> should be ok for newConfig.paths.source.css:
     Error: should be ok for newConfig.paths.source.css
      at Test.<anonymous> (test/replace_config_paths.test.js:25:9)
      at Object.<anonymous> (test/replace_config_paths.test.js:6:5)

  26) ./test/replace_config_paths.test.js replaceConfigPaths -> should be ok for newConfig.paths.public.root:
     Error: should be ok for newConfig.paths.public.root
      at Test.<anonymous> (test/replace_config_paths.test.js:34:7)
      at Object.<anonymous> (test/replace_config_paths.test.js:6:5)

  27) ./test/replace_config_paths.test.js replaceConfigPaths -> should be ok for newConfig.paths.public.patterns:
     Error: should be ok for newConfig.paths.public.patterns
      at Test.<anonymous> (test/replace_config_paths.test.js:34:7)
      at Object.<anonymous> (test/replace_config_paths.test.js:6:5)

  28) ./test/replace_config_paths.test.js replaceConfigPaths -> should be ok for newConfig.paths.public.data:
     Error: should be ok for newConfig.paths.public.data
      at Test.<anonymous> (test/replace_config_paths.test.js:34:7)
      at Object.<anonymous> (test/replace_config_paths.test.js:6:5)

  29) ./test/replace_config_paths.test.js replaceConfigPaths -> should be ok for newConfig.paths.public.annotations:
     Error: should be ok for newConfig.paths.public.annotations
      at Test.<anonymous> (test/replace_config_paths.test.js:34:7)
      at Object.<anonymous> (test/replace_config_paths.test.js:6:5)

  30) ./test/replace_config_paths.test.js replaceConfigPaths -> should be ok for newConfig.paths.public.styleguide:
     Error: should be ok for newConfig.paths.public.styleguide
      at Test.<anonymous> (test/replace_config_paths.test.js:34:7)
      at Object.<anonymous> (test/replace_config_paths.test.js:6:5)

  31) ./test/replace_config_paths.test.js replaceConfigPaths -> should be ok for newConfig.paths.public.js:
     Error: should be ok for newConfig.paths.public.js
      at Test.<anonymous> (test/replace_config_paths.test.js:34:7)
      at Object.<anonymous> (test/replace_config_paths.test.js:6:5)

  32) ./test/replace_config_paths.test.js replaceConfigPaths -> should be ok for newConfig.paths.public.images:
     Error: should be ok for newConfig.paths.public.images
      at Test.<anonymous> (test/replace_config_paths.test.js:34:7)
      at Object.<anonymous> (test/replace_config_paths.test.js:6:5)

  33) ./test/replace_config_paths.test.js replaceConfigPaths -> should be ok for newConfig.paths.public.fonts:
     Error: should be ok for newConfig.paths.public.fonts
      at Test.<anonymous> (test/replace_config_paths.test.js:34:7)
      at Object.<anonymous> (test/replace_config_paths.test.js:6:5)

  34) ./test/replace_config_paths.test.js replaceConfigPaths -> should be ok for newConfig.paths.public.css:
     Error: should be ok for newConfig.paths.public.css
      at Test.<anonymous> (test/replace_config_paths.test.js:34:7)
      at Object.<anonymous> (test/replace_config_paths.test.js:6:5)

  35) ./test/replace_config_paths.test.js replaceConfigPaths -> should be ok for newConfig.patternExportDirectory:
     Error: should be ok for newConfig.patternExportDirectory
      at Test.<anonymous> (test/replace_config_paths.test.js:39:5)
      at Object.<anonymous> (test/replace_config_paths.test.js:6:5)

and this was the coverage

------------------------|----------|----------|----------|----------|-------------------|
File                    |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
------------------------|----------|----------|----------|----------|-------------------|
All files               |    75.29 |       49 |    62.34 |    75.89 |                   |
 bin                    |    72.99 |    48.53 |    60.78 |    73.61 |                   |
  archive.js            |    52.94 |       50 |    33.33 |    52.94 |... 29,34,35,40,42 |
  ask.js                |    53.33 |        0 |        0 |    53.33 |... 26,31,34,35,38 |
  build.js              |    91.67 |    83.33 |      100 |    91.67 |                14 |
  install-edition.js    |    36.36 |        0 |    66.67 |     37.5 |... ,97,98,101,105 |
  install-plugin.js     |    88.24 |       50 |      100 |    88.24 |             24,25 |
  install-starterkit.js |    93.33 |       75 |      100 |    93.33 |                21 |
  patternlab.js         |    82.05 |      100 |       50 |    85.71 |  28,29,30,147,150 |
  replace-config.js     |      100 |       75 |      100 |      100 |                29 |
  resolve-config.js     |    84.21 |      100 |      100 |    84.21 |          36,39,40 |
  scaffold.js           |      100 |       50 |      100 |      100 |                20 |
  serve.js              |     62.5 |       70 |      100 |     62.5 | 16,38,39,40,41,43 |
  utils.js              |    74.24 |    46.67 |    52.38 |    74.24 |... 93,194,195,198 |
  validate-config.js    |       50 |        0 |        0 |       50 |                 9 |
 bin/cli-actions        |    79.86 |       50 |    73.91 |    80.43 |                   |
  build.js              |    90.91 |      100 |      100 |    90.91 |                11 |
  disable.js            |       90 |    66.67 |      100 |       90 |             29,30 |
  enable.js             |       90 |    66.67 |      100 |       90 |             29,30 |
  export.js             |      100 |      100 |      100 |      100 |                   |
  help.js               |       50 |      100 |        0 |       50 |                 4 |
  init.js               |    67.44 |       25 |    66.67 |    69.05 |... 72,73,78,83,86 |
  install.js            |    79.17 |     62.5 |    66.67 |    79.17 |    23,25,26,27,37 |
  serve.js              |     62.5 |      100 |        0 |     62.5 |             7,8,9 |
  version.js            |      100 |      100 |      100 |      100 |                   |
 bin/inquiries          |       75 |      100 |        0 |       75 |                   |
  confirm.js            |      100 |      100 |      100 |      100 |                   |
  edition.js            |       60 |      100 |        0 |       60 |             10,32 |
  starterkit.js         |       80 |      100 |        0 |       80 |                46 |
------------------------|----------|----------|----------|----------|-------------------|

**Comment by bmuenzenmeyer** [comment]
I think we can start chipping away at these failures and get them to a point where we turn back on the tests. I used the `scaffold` tests locally this morning to validate some functionality. There is a LOT of good still here!
