### ISSUE TITLE
[core] PL3 doesn't handle identical type and pattern names

### ISSUE THREAD

**Issue by engelfrost** [pattern-lab/patternlab-node#888]
I am using Pattern Lab Node `v3.0.0-alpha.16` on `Mac`, with Node `v9.6.1`, using a `Vanilla` Edition.

PL3 cannot handle the case when when pattern type and pattern name are identical (e.g. 01-atoms/02-foo/03-atoms.mustache)

##### Expected Behavior

To be able to create a pattern that shares the same name as the pattern type

##### Actual Behavior

PL build breaks if I create a pattern with the same name as the pattern type, e.g. `01-atoms/10-buttons/atoms.mustache` will produce this output: 

```
Built pattern: atoms-atoms
```
...
```
e =  TypeError: Cannot read property 'patternSectionSubtype' of undefined
    at Context.lookup (/Users/josef/Code/fabrikor/node_modules/mustache/mustache.js:404:31)
    at Writer.renderSection (/Users/josef/Code/fabrikor/node_modules/mustache/mustache.js:503:25)
    at Writer.renderTokens (/Users/josef/Code/fabrikor/node_modules/mustache/mustache.js:486:40)
    at Writer.renderSection (/Users/josef/Code/fabrikor/node_modules/mustache/mustache.js:515:24)
    at Writer.renderTokens (/Users/josef/Code/fabrikor/node_modules/mustache/mustache.js:486:40)
    at Writer.render (/Users/josef/Code/fabrikor/node_modules/mustache/mustache.js:465:17)
    at Object.render (/Users/josef/Code/fabrikor/node_modules/mustache/mustache.js:601:26)
    at Object.renderPattern (/Users/josef/Code/fabrikor/node_modules/@pattern-lab/engine-mustache/lib/engine_mustache.js:54:20)
    at Pattern.render (/Users/josef/Code/fabrikor/node_modules/@pattern-lab/core/src/lib/object_factory.js:128:35)
    at module.exports (/Users/josef/Code/fabrikor/node_modules/@pattern-lab/core/src/lib/render.js:13:18)
TypeError: Cannot read property 'patternSectionSubtype' of undefined
    at Context.lookup (/Users/josef/Code/fabrikor/node_modules/mustache/mustache.js:404:31)
    at Writer.renderSection (/Users/josef/Code/fabrikor/node_modules/mustache/mustache.js:503:25)
    at Writer.renderTokens (/Users/josef/Code/fabrikor/node_modules/mustache/mustache.js:486:40)
    at Writer.renderSection (/Users/josef/Code/fabrikor/node_modules/mustache/mustache.js:515:24)
    at Writer.renderTokens (/Users/josef/Code/fabrikor/node_modules/mustache/mustache.js:486:40)
    at Writer.render (/Users/josef/Code/fabrikor/node_modules/mustache/mustache.js:465:17)
    at Object.render (/Users/josef/Code/fabrikor/node_modules/mustache/mustache.js:601:26)
    at Object.renderPattern (/Users/josef/Code/fabrikor/node_modules/@pattern-lab/engine-mustache/lib/engine_mustache.js:54:20)
    at Pattern.render (/Users/josef/Code/fabrikor/node_modules/@pattern-lab/core/src/lib/object_factory.js:128:35)
    at module.exports (/Users/josef/Code/fabrikor/node_modules/@pattern-lab/core/src/lib/render.js:13:18)
```

##### Steps to Reproduce

Create a template file which shares the name of its pattern type

**Comment by bmuenzenmeyer** [comment]
Workaround until fixed (if ever): don't name a pattern the same as its group.

**Comment by JosefBredereck** [comment]
In the current version, this issue seems to be resolved.
