### ISSUE TITLE
[core] PL3 does not like pattern parameters with dashes

### ISSUE THREAD

**Issue by engelfrost** [pattern-lab/patternlab-node#889]
I am using Pattern Lab Node `v3.0.0-alpha.16` on `Mac`, with Node `v9.6.1`, using a `Vanilla` Edition.

Not sure if using dashes is an intentional or accidental feature, and if this issue is to be considered a  bug or a breaking change. 

Removing dashes seems to help both when using Mustache and Handlebars. However, I get different error messages. I suspect that dashes are not allowed in Handlebars, and that `engine-handlebars` silently fails, causing `core` to fail as well. 

##### Expected Behavior

That the pattern is generated just like in PL2. 

##### Actual Behavior

When using Mustache:

`patternlab build --config ./patternlab-config.json` fails:

```
SyntaxError: Invalid regular expression: /{{{?\s*[alt-icon]+\s*}?}}/: Range out of order in character class
    at new RegExp (<anonymous>)
    at module.exports (/Users/josef/Code/fabrikor-mustache/node_modules/@pattern-lab/core/src/lib/replaceParameter.js:8:19)
    at previousPromise.then (/Users/josef/Code/fabrikor-mustache/node_modules/@pattern-lab/core/src/lib/parameter_hunter.js:308:51)
    at <anonymous>
SyntaxError: Invalid regular expression: /{{{?\s*[alt-icon]+\s*}?}}/: Range out of order in character class
```

When using Handlebars:

```
e =  TypeError: Cannot read property 'patternSectionSubtype' of undefined
    at Context.lookup (/Users/josef/Code/fabrikor/node_modules/mustache/mustache.js:404:31)
    at Writer.renderSection (/Users/josef/Code/fabrikor/node_modules/mustache/mustache.js:503:25)
    at Writer.renderTokens (/Users/josef/Code/fabrikor/node_modules/mustache/mustache.js:486:40)
    at Writer.renderSection (/Users/josef/Code/fabrikor/node_modules/mustache/mustache.js:515:24)
    at Writer.renderTokens (/Users/josef/Code/fabrikor/node_modules/mustache/mustache.js:486:40)
    at Writer.render (/Users/josef/Code/fabrikor/node_modules/mustache/mustache.js:465:17)
    at Object.render (/Users/josef/Code/fabrikor/node_modules/mustache/mustache.js:601:26)
    at Object.renderPattern (/Users/josef/Code/fabrikor/node_modules/@pattern-lab/engine-mustache/lib/engine_mustache.js:54:20)
    at Pattern.render (/Users/josef/Code/fabrikor/node_modules/@pattern-lab/core/src/lib/object_factory.js:128:35)
    at module.exports (/Users/josef/Code/fabrikor/node_modules/@pattern-lab/core/src/lib/render.js:13:18)
TypeError: Cannot read property 'patternSectionSubtype' of undefined
    at Context.lookup (/Users/josef/Code/fabrikor/node_modules/mustache/mustache.js:404:31)
    at Writer.renderSection (/Users/josef/Code/fabrikor/node_modules/mustache/mustache.js:503:25)
    at Writer.renderTokens (/Users/josef/Code/fabrikor/node_modules/mustache/mustache.js:486:40)
    at Writer.renderSection (/Users/josef/Code/fabrikor/node_modules/mustache/mustache.js:515:24)
    at Writer.renderTokens (/Users/josef/Code/fabrikor/node_modules/mustache/mustache.js:486:40)
    at Writer.render (/Users/josef/Code/fabrikor/node_modules/mustache/mustache.js:465:17)
    at Object.render (/Users/josef/Code/fabrikor/node_modules/mustache/mustache.js:601:26)
    at Object.renderPattern (/Users/josef/Code/fabrikor/node_modules/@pattern-lab/engine-mustache/lib/engine_mustache.js:54:20)
    at Pattern.render (/Users/josef/Code/fabrikor/node_modules/@pattern-lab/core/src/lib/object_factory.js:128:35)
    at module.exports (/Users/josef/Code/fabrikor/node_modules/@pattern-lab/core/src/lib/render.js:13:18)
```

##### Steps to Reproduce

Use parameters including dashes when including a pattern:

Mustache:
```mustache
{{>atoms-icon-button(icon: 'chevron-up', alt-icon: 'chevron-down')}}
```

Handlebars:
```handlebars
{{>atoms-icon-button icon='chevron-up' alt-icon='chevron-down'}}
```

**Comment by bmuenzenmeyer** [comment]
Workaround until fixed: don't use them

**Comment by engelfrost** [comment]
IMHO that workaround can be considered the solution if you like. Simply define it as one of the breaking changes.

**Comment by bmuenzenmeyer** [comment]
Well I briefly looked into the mustache spec and it looked supported.  Needs more investigation on my part.  Another reason to get out of the business of extended syntaxes.

**Comment by engelfrost** [comment]
Strictly speaking pattern parameters is not part of the mustache spec, right? Although it might seem a little odd that dashes would allowed in keys but not in parameters.

**Comment by JosefBredereck** [comment]
I tested that with the current version with handlebars engine. There the issue seems to be gone.
