### ISSUE TITLE
Recursive templates not working

### ISSUE THREAD

**Issue by svalchinov** [pattern-lab/patternlab-node#987]
I am using Pattern Lab Node `v2.12.0` on `Windows`, with Node `v11.6.0`, using a `Gulp` Edition.

##### Expected Behavior

Expecting the following mustache behaviour (e.g. recursive templates) to work.
https://jsfiddle.net/q62jek5d/

##### Actual Behavior
```
Incremental builds enabled.
RangeError: Maximum call stack size exceeded
    at normalizeString (path.js:52:25)
    at Object.resolve (path.js:1095:20)
    at Function.Module._resolveLookupPaths (internal/modules/cjs/loader.js:499:17)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:596:20)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at new parameter_hunter (.../pattern-lab/node_modules/patternlab-node/core/lib/parameter_hunter.js:6:10)
    at expandPartials (.../pattern-lab/node_modules/patternlab-node/core/lib/pattern_assembler.js:450:26)
    at decomposePattern (.../pattern-lab/node_modules/patternlab-node/core/lib/pattern_assembler.js:240:7)
```

##### Steps to Reproduce
Actual code I used:

parent.mustache
```
<ul>
    {{#menu}}
        <li>
            {{item}} {{> recurse }}
        </li>
    {{/menu}}
</ul>
```
recurse.mustache
```
<ul class="submenu">
    {{#menu}}
        <li>
            {{item}} {{>recurse}}
        </li>
    {{/menu}}
</ul>
```

relevant data.json
```
"menu": [{
      "item": "parent",
      "menu": [
        {
          "item": "sub child",
          "menu": [
            {
              "item": "sub sub child",
              "menu": null
            }]
        }]
    }]

```

**Comment by engelfrost** [comment]
Hi! 
I'm sorry for the lack of replies. AFAIK not allowing recursive patterns is by design. 

The technical reason is that it would enable infinite recursion (but there are strategies to deal with this of course). But more importantly, it breaks the hierarchical structure. The design philosophy behind PL says that "recurse" should only include patterns lower down in the hierarchy. 

That said, I get what you're doing and I've tried to do the same thing myself. I've resorted to simply limiting the depth my patterns support and making loops in my templates. I'm using Handlebars, perhaps there are engines that allow more powerful solutions.
